
# Introduction {-}

<p align="justify">Underemployment is a growing worrying feature of the UK labour market. Workers who are underemployed are working below their potential or preference in terms of the hours spent in work, the wages earned and/or the skills they use in their jobs. Our study is tracking levels of underemployment over time in the UK and across Europe. We are detailing the composition of the underemployed workforce, pinpointing the predictors of being underemployed and its outcomes, and highlighting the lived experiences of underemployed workers in four UK cities.</p>

<p align="justify">In this first project report we address key questions around how we can understand and best measure underemployment. The report examines if and how individual indicators of underemployment overlap and whether they accumulate over time and for whom. We ask about the characteristics of those workers who experience various forms and combinations of underemployment, as well as those with no underemployment at all. We approach underemployment as a complex and multidimensional phenomenon including insufficient hours of employment, low wages, and limited use of skills at work.</p>

<p align="justify">Our approach is advancing how we understand and measure underemployment. Most official measures of underemployment are limited to hours worked. Time-related underemployment exists when the hours of work of an employed person are insufficient in relation to an alternative employment situation in which the person is willing and available to engage. While time-related underemployment is very important, a one-dimensional understanding of underemployment does not provide any information on the adequacy of a person’s wages and skills usage. The limitation of time-related underemployment is evident, for instance, in the case of workers who, although having a full-time job and are happy with the number of hours that they work, have low wages or may feel that their skills as underutilised. In this report, we innovatively consider all these three indicators and their interaction to provide a complete picture of underemployment in the UK. </p>
