
# Introduction {-}

<p align="justify">Underemployment is an increasingly concerning feature of the UK labour market. Workers who are underemployed are working below their potential or preference in terms of the hours spent in work, the wages earned and/or the skills they use in their jobs. Our study is tracking underemployment levels in the UK and across Europe. We are identifying the demographic characteristics of underemployed workers, determining the predictors of underemployment and its consequences, and highlighting the lived experiences of underemployed individuals in four UK cities.</p>

<p align="justify">In this first project report we address key questions around how we can measure underemployment and track it over time. The report examines trends in the levels of various forms of underemployment since 2006, analysing gender, ethnic, occupational, qualification, regional and industry disparities in these trends. We approach underemployment as a complex and multidimensional phenomenon including insufficient hours of employment, limited use of skills at work and/or low wages.</p>

<p align="justify">Our approach advances the understanding of the measurement of underemployment. Most official measures of underemployment are limited to hours worked. Time-related underemployment exists when the hours of work of an employed person are insufficient in relation to an alternative employment situation in which the person is willing and available to engage. While time-related underemployment is very important, a one-dimensional understanding of underemployment does not provide any information on the adequacy of a person’s wages and skills usage. The limitation of time-related underemployment is evident, for instance, in the case of workers who, although having a full-time job and are happy with the number of hours that they work, have low wages or may feel that their skills as underutilised. In this report, we innovatively consider all these three indicators to provide a complete picture of underemployment in the UK. Our second report will focus on exploring these indicators in combination.</p>
